#cloud-config
hostname: db-navrotskyi
manage_etc_hosts: localhost

write_files:
  - path: /opt/seo-auditor/.env
    permissions: '0600'
    content: |
      DB_USER=seoauditor
      DB_PASSWORD=__INSERT_DB_PASSWORD__
      DB_NAME=seoauditor

runcmd:
  - [ sh, -c, "until getent hosts github.com >/dev/null; do echo 'wait dns'; sleep 3; done" ]
  - [ sh, -c, "for i in 1 2 3 4 5; do git clone https://github.com/MarshallBjorn/SEO-Checker /opt/seo-auditor && break || sleep 5; done" ]
  - [ sh, -c, "cd /opt/seo-auditor && docker compose --env-file .env -f compose/docker-compose.db.yml up -d" ]

final_message: "db-navrotskyi up after $UPTIME seconds"
